### ISSUE TITLE
demo.py运行报错

### ISSUE THREAD

**Issue by zchrissirhcz** [myhub/uc#1]
## 环境
MacOS
python 3.7 (anaconda)

## 步骤
```
pip install uc
cd ~/work
git clone https://github.com/myhub/uc
cd uc/examples
python demo.py
```

## 报错
```
⚡ python demo.py
(5000, 1) (5000, 1)
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    mlp = MLP(layer_size=[X.shape[1], 8, 8, 8, 1], rate_init=0.02, loss_type="mse", epoch_train=100, epoch_decay=10, verbose=1)
  File "/Users/chris/soft/miniconda3/lib/python3.7/site-packages/uc/mlp.py", line 47, in __init__
    self.mesh_init(dtype=self.params_.get('dtype', 'float64'))
  File "/Users/chris/soft/miniconda3/lib/python3.7/site-packages/uc/mesh.py", line 33, in mesh_init
    self.load_library(dtype)
  File "/Users/chris/soft/miniconda3/lib/python3.7/site-packages/uc/mesh.py", line 67, in load_library
    raise NotImplementedError()
NotImplementedError
Exception ignored in: <function Mesh.__del__ at 0x127c7d560>
Traceback (most recent call last):
  File "/Users/chris/soft/miniconda3/lib/python3.7/site-packages/uc/mesh.py", line 30, in __del__
    self.destroy()
  File "/Users/chris/soft/miniconda3/lib/python3.7/site-packages/uc/mesh.py", line 142, in destroy
    self._libc.mesh_destroy(self.mi_)
AttributeError: 'NoneType' object has no attribute 'mesh_destroy'
```

**Comment by myhub** [comment]
暂时只支持了linux，后续会支持windows macos
