### ISSUE TITLE
Linux is also not supported

### ISSUE THREAD

**Issue by zchrissirhcz** [myhub/uc#2]
你好，我在ubuntu16.04上试验的

miniconda安装的python 3.7

运行demo.py报错如下：

```
(5000, 1) (5000, 1)
uc 0.2.1
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    mlp.fit(X, Y)
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/uc/mlp.py", line 266, in fit
    score = self.get_score(eval_set, eval_metric)
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/uc/mlp.py", line 185, in get_score
    score = sklearn.metrics.accuracy_score(eval_set[1], y_pred)
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/zz/soft/miniconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 88, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: continuous is not supported

```

**Comment by zchrissirhcz** [comment]
老铁，你这在MacOS和Linux下都报错，发布前是怎么测试的，用的什么环境

**Comment by myhub** [comment]
我检查了一下，目前我发布的最新版本是2.1.5，不知道为什么安装的是0.2.1版本
https://pypi.org/project/uc/

**Comment by zchrissirhcz** [comment]
@myhub 我用的阿里云的pypi源。把~/.pip/pip.conf删除后再pip install uc，安装的是最新的2.1.5
镜像的锅

**Comment by zchrissirhcz** [comment]
@myhub 
https://github.com/tuna/issues/issues/467
